###
POST http://localhost:8080/articles/add
Content-Type: application/json

{
  "id": 0,
  "title": "Shok xabar",
  "author": "Ahad Qayum",
  "content": "Lorem ipsum"
}

###
GET http://localhost:8080/articles/all

###
GET http://localhost:8080/articles/{id}

###
PUT http://localhost:8080/articles/update/{id}

###
DELETE http://localhost:8080/articles/delete/{id}